apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: postgres
profiles:
  - name: local
    manifests:
      helm:
        releases:
          - name: postgres
            chartPath: chart
            valuesFiles:
              - chart/values.yaml
    deploy:
      kubectl: {}
