apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: auth-provider
build:
  artifacts:
    - image: auth-provider
      context: .
      docker:
        dockerfile: Dockerfile
profiles:
  - name: local
    manifests:
      helm:
        flags:
          install:
            - --atomic
          upgrade:
            - --atomic
        releases:
          - name: auth-provider
            chartPath: chart
            wait: true
            valuesFiles:
              - chart/values.yaml
              - chart/values-local.yaml
    deploy:
      statusCheckDeadlineSeconds: 700
      statusCheck: true
      helm:
        flags:
          install:
            - --atomic
          upgrade:
            - --atomic
  - name: dev
    manifests:
      helm:
        releases:
          - name: auth-provider
            chartPath: chart
            valuesFiles:
              - chart/values.yaml
              - chart/values-dev.yaml
  - name: prod
    manifests:
      helm:
        releases:
          - name: auth-provider
            chartPath: chart
            valuesFiles:
              - chart/values.yaml
              - chart/values-prod.yaml
